### PR TITLE
Rework containers

### PR DESCRIPTION
**Pull request by Alainx277**
### Summary

Completely reworks the container/inventory system. It is now fully networked, while remaining secure against cheating.
It also makes containers 2 dimensional.
Adds proper clothing slots.

## Pictures/Videos

image

image

## Changes to Files

Everything that has to do with containers.

## Technical Notes

I'll create a wiki article to explain the system.

## Known issues

The store interaction is not working, and I think we should remove it for anything that has more than 1 slot.
Anything attached to the tilemap does not network, but that is not related to this PR.

## Fixes

Partly #332

### CODE REVIEW

**Comment by DoomsdayOrange** [comment]
- The bike horn disappears when placed into a container, making it unretrievable. Doesn't seem like any other item is affected by this bug.
- The hardhat also vanishes when equipped, but is still recoverable.

**Review by henkhooft — CHANGES_REQUESTED** [review]
Overall looks pretty good. Though a few points of improvement:

### Bugs
**Null pointer when clicking armor slot**
Steps to reproduce:

1. Grab any item
2. Click the armor slot on the player



**Removing items from container clips them into the floor**
Steps to reproduce:

1. Place an item in a container
2. Drag the item outside of the inventory GUI

**Server crash during container sync**
Steps to reproduce:

1. Play around with a container
2. Unknown cause crashes it at some point
afbeelding

### Small potential improvements

- Remove the debug.log when canvas limits are reached
- Being able to interact with an item when active in hand (for example enabling the flashlight from hand)
- Slots sizes are always 1x1. Is this correct?
- Lots of components added for a single container. Would be nice to simplify that into a single component that can be added.

afbeelding

**Comment by Alainx277** [comment]
I couldn't reproduce the server crash.
The many components are intentional, as not all containers are going to need all features/options, and some will need multiple containers.
Slot sizes aren't defined yet, because it is a balancing issue, they default to 1x1.

Everything else should be fixed.

**Comment by cosmiccoincidence** [comment]
> The many components are intentional, as not all containers are going to need all features/options, and some will need multiple containers.


Couldn't this still be consolidated and in the component have an option to use what part is needed for that specific prefab? Maybe a box to check or a drop-down menu to hide parts that are not needed. Just an idea.

**Review by henkhooft — APPROVED** [review]
Well done 👍

**Pull request merged**
