### PR TITLE
Fix broken CI tests

### LINKED ISSUE #1322: Github CI tests are broken
## Summary

Tests automatically fail due to some issues with github actions. The tests have this warning in the logs
image

Github made a note: 
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Fix the CI tests please

### PR DESCRIPTION
**Pull request by gouravmpk**
# Summary

Added the code needed to run node 16 in the tests workflows

# Related issues/PRs 

 closes #1322

### CODE REVIEW

**Comment by stilnat** [comment]
I'm worried this break soon : 
"Following on from our [warning in workflows using Node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) we will start enforcing the use of Node16 rather than Node12 on the 14th of June."

Github says : 
**This will only work until we upgrade the runner removing Node12 later in the summer.**

They are late apparently, but we need to go with the node16 thing

**Comment by gouravmpk** [comment]
If you need to update your GitHub Actions workflow to use Node.js version 16 and ensure compatibility with the upcoming changes, I can modify your workflow YAML accordingly.
cc:@stilnat

**Comment by cosmiccoincidence** [comment]
Please add a description (summary) and title to your pr.

**Comment by stilnat** [comment]
@gouravmpk please do if you know how to deal with it.

**Review by stilnat — APPROVED** [review]
merging this for now, will check if that works. If it does, all good, bounty is yours ! @gouravmpk are you on our discord or are you just passing by ? @Dennis-Nesterenko (probably not on discord) is in charge of the money.

**Comment by gouravmpk** [comment]
> merging this for now, will check if that works. If it does, all good, bounty is yours ! @gouravmpk are you on our discord or are you just passing by ? @Dennis-Nesterenko (probably not on discord) is in charge of the money.

I am on Discord just joined

**Comment by cosmiccoincidence** [comment]
> > merging this for now, will check if that works. If it does, all good, bounty is yours ! @gouravmpk are you on our discord or are you just passing by ? @Dennis-Nesterenko (probably not on discord) is in charge of the money.
> 
> I am on Discord just joined

What is your Discord name?

**Comment by gouravmpk** [comment]
> > > merging this for now, will check if that works. If it does, all good, bounty is yours ! @gouravmpk are you on our discord or are you just passing by ? @Dennis-Nesterenko (probably not on discord) is in charge of the money.
> > 
> > 
> > I am on Discord just joined
> 
> What is your Discord name?

SILVER
werewolf#9296

**Pull request merged**
