### PR TITLE
Updates Documents & GitHub

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
### Summary

Updates some documentation.

(Ignore the huge number of commits, most of them were me making small changes to the readme file and testing how it looked)

### Changes to Files 

- Updates 'bug' issue template
- Reworks current 'task' issue template into a 'feature' issue template
- Adds 'documentation' and 'suggestion' templates
- Added issue template config file, allowing for linking to external sites via the issue template system
- Adds a funding file that places a link to any listed funding sources on the right side of the repo home page. If this looks good maybe we will move all the donation links there. (I couldn't visually test this so we just have to see if it works, though [unitystation](https://github.com/unitystation/unitystation) has it on their repo if you want to see what it *should* look like).
- Updates the readme file with some neat github and social media stats ([see it working here](https://github.com/cosmiccoincidence/SS3D/tree/templates#-welcome-to-the-offical-repository-for-re-space-station-3d-the-game-ress3d-is-an-open-source-resurrection-of-the-original-ss3d-project-which-was-an-impressive-demo-attempting-to-give-the-infamous--an-extra-dimension))
- Updates contribution file

### Not directly part of this PR but changes to the Github I recently made:

- Added the [discussions page](https://github.com/RE-SS3D/SS3D/discussions) to github and got some discussions going.
- Made a custom sidebar on the [wiki](https://github.com/RE-SS3D/SS3D/wiki) and just added links to the website and Google Drive to it for now. 
image
- Reworked the [github labels](https://github.com/RE-SS3D/SS3D/labels) by looking at several ss13 codebases and remakes and even some other games and summarized the popular labels and tailored them to our game. I then renamed our current labels to fit into this rework to save time on linking them again afterward. I replaced our dozen or so general labels with 80 more specific ones, this may seem kinda high and on some issues the labels section gets kinda crowded but from looking at other popular game repos, this isn't uncommon.

Please give these github changes a look as well, especially the labels. I added a bunch of labels and one contributing factor to that is becuase I moved the system-specific github projects (atmospherics, constructions, user interface, ect.) from github projects to github labels (this seems to be the popular choice among ss13 codebases, ss13 remakes, and some other open-source games). I likely didn't cover all the primary systems and we may need to add more labels to account for them. The color choices for the labels were done in a hurry so let me know if you have any suggestions on those.

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Feel free to review this, the ONLY thing I need to do still is work on adding new issue labels which isn't directly part of this PR. The reason I'm keeping this PR open for now is that its possible I may end up renaming current labels in the process which would break the link between them and the templates (so just a minor error but still).

**Comment by DoomsdayOrange** [comment]
Looks good. The only issue is that the formatting in readme gets all screwed up when viewing from a mobile device but I don't really see that as that important of an problem.

**Review by DoomsdayOrange — COMMENTED** [review]
Looks good. The only issue is that the formatting in readme gets all screwed up when viewing from a mobile device but I don't really see that as that important of an problem.

**Review by DoomsdayOrange — APPROVED** [review]
Looks good. The only issue is that the formatting in readme gets all screwed up when viewing from a mobile device but I don't really see that as that important of an problem.

**Pull request merged**
