### PR TITLE
Bad banana

### PR DESCRIPTION
**Pull request by Alainx277**
### Summary

Banana go slip
Also soap goes slip too

## Pictures/Videos

image

## Known issues

Exact ragdoll position is not synced

## Fixes

The severe lack of banana peel related slipping.

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Add this to the soap too, please.

**Comment by Alainx277** [comment]
Seems like I'm missing the interaction attacher in my branch. I think it might be good to wait for the interaction change to be merged, otherwise I'll just have more conflicts later.

**Comment by cosmiccoincidence** [comment]
I recommend not committing the main scene file as there will be some major conflicts by the time this is ready.

**Comment by Alainx277** [comment]
> I recommend not committing the main scene file as there will be some major conflicts by the time this is ready.

I moved the peel to the floor, I'll just let my changes be overwritten.

**Pull request merged**
