### PR TITLE
Organize 'Assets' folder

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
## Purpose
Organizes the 'Assets' folder a bit while paralleling the onedrive's asset folder structure as well.

## Changes To Existing Files
Only moves files/folders.

## Media

[changes](https://i.imgur.com/KGyZtu2.png)

[the final draft](https://1drv.ms/t/s!AkL13ubt2eYmsbQdvs8BvSY-8qEccQ)

## Known Issues
Will likely cause file conflicts with other open PRs.

## Additional Context
Ready for review, still has conflicts with Nonanon's recent changes.

### CODE REVIEW

**Comment by TimFinucane** [comment]
Suggestion: Show before and after picture/diagram of structure in the review description

**Comment by cosmiccoincidence** [comment]
Sure, I'll do that when this is ready for review. Still need to figure out the deal with the 'resources' folder and sort the 'code' folder first.

**Comment by TimFinucane** [comment]
I don't like the idea of the textures being in 2D, more because even though they are 2d, they're used on 3d things. If I was working from unity I would expect all stuff used for a given 3d object to be in the 3d folder.

If there are prefabs in 3D, there should be prefabs in 2D. Is UI in 2D? What about prefabs that aren't 3D or 2D (e.g. the network manager)?

Also just mentioning i still think models, animations, textures, and materials should be merged as much as possible, even though i know you won't implement it.

**Comment by cosmiccoincidence** [comment]
> I don't like the idea of the textures being in 2D, more because even though they are 2d, they're used on 3d things. If I was working from unity I would expect all stuff used for a given 3d object to be in the 3d folder.
I guess the way I see it is, if a 2D artist just wants to implement some new poster textures, the folder should be in the most logical place to find it for someone who doesnt know the whole project structure.
> If there are prefabs in 3D, there should be prefabs in 2D. Is UI in 2D? What about prefabs that aren't 3D or 2D (e.g. the network manager)?
Are there 2D prefabs? Even so, a flat prefab for some kind of decal I'd still consider 3D as it's placed in 3D.
UI is in 2D > Graphics.
But if it is such a broad category to include non-2d or 3d prefabs, then I can move it back out of 3D and just leave it in Assets.
> Also just mentioning i still think models, animations, textures, and materials should be merged as much as possible, even though i know you won't implement it.
I just see it as looking overwhelming to the average (lets say) artist, who just want to update a computer .fbx, but the folder has .fbx, .asset, .meta, textures, animations, etc., etc. all in the same folder.
That being said I'm not 100% against this.

**Comment by TimFinucane** [comment]
I could see the .asset and .prefabs potentially being separated from the 'art assets', but I would think if I was an artist it'd be much easier for me to go to, e.g. the Computer (furniture) folder, see the texture and the fbx in there, edit the model and then check that it still worked with the texture.

**Comment by cosmiccoincidence** [comment]
I reworked everything again to a new structure which I'm posting a condensed version of it here (but I updated the more complete changes in the PR description).


notepad_fkZZSKWx5N

**Comment by cosmiccoincidence** [comment]
Renamed the 'Structure' folder in 'SFX' to 'Structures'.

I think it should be good now besides the conflicts.

**Comment by cosmiccoincidence** [comment]
Actually done now. And updated the files in the description.

**Comment by TimFinucane** [comment]
Will need more time to make the changes, but I think that Scripts needs to be removed, Engine and Content should come under a 'Code' folder. Some folders are missing, others seem out of place (why is Content/Players, which is only code, right next to Content/Materials?).

Some folders need to be renamed too, e.g. ItemComponents, Engine/Enums.

**Comment by cosmiccoincidence** [comment]
> Scripts needs to be removed

I did that already.

> Engine and Content should come under a 'Code' folder.

That's do-able

> Some folders are missing

Like what?

> others seem out of place (why is Content/Players, which is only code, right next to Content/Materials?).

Not sure. So do you propose something like this then?
```
Content
   ...
Code
   Content
      ...
   Engine
      ...
```

Also @onebigames had some input in the structure so I'll wai to for his input again.

> Some folders need to be renamed too, e.g. ItemComponents, Engine/Enums.

Can I get a breakdown of what needs to be renamed?

**Comment by TimFinucane** [comment]
Well i'm not sure why materials are being placed with code, materials seem more like an art thing. I can kinda see prefabs being with code, but at the same time it might be more clear to separate code-like content from other content, especially if we're doing the same for art.

After than I want to rename ItemComponents.

I will need to rename Content/Resources to something else to reflect it contains assets.

Another question - Is it worth it separating 2D and 3D into two different folders if the contents are all different anyway? that is, we could just do:

- Art
    - Graphics
    - Textures
    - Animations
    - Models
    - Shaders
    - Sound

I think its still pretty unambiguous what is 2d and what is 3d.

I think most of the renames I was thinking of were in the code folders, so i'll do them afterwards.

**Comment by cosmiccoincidence** [comment]
Combined the Art folders.
Added the Materials folder to the Art folder.
Added a Code sub folder to the Content folder and moved Player and ItemComponent folders there.
Did some sorting to Prefabs and Materials and got rid of old shit.

**Comment by TimFinucane** [comment]
One more thing:
- Items/Functional/Tools -> Items/Tools
- Items/Functional/Generic -> Remove?
- Items/Functional/Tools/Generic -> Remove?

I don't think the 'Generic' and 'Functional' folder names are that informative.

**Comment by TimFinucane** [comment]
Partially finished. Still need to:
- Update namespaces in 'Chat', 'Health', 'Server'.
- Merge Code, Prefabs, and .assets in a sensical way

**Comment by cosmiccoincidence** [comment]
> I don't think the 'Generic' and 'Functional' folder names are that informative.

Some of the vocab I carried over form the previous folder structure, if you have better names in mind, I'm all ears. But in sorting in the models list on trello, this is the conclusion I came too. I'm providing a snap showing the Items folder with the Functional subfolder expanded. It's taken from the 'final draft' document I have linked in the pr description. And if you are curious as to what is in some of these categories/groups look at the model list on trello as you can quickly see these categories there. Again my ears are open if you have suggestions on it. I've been trying my best to keep the models list updated and the keep that final draft updated too.

**Comment by TimFinucane** [comment]
Given the size of the functional folder, this looks kinda fine. Some other ways of splitting up though are:

- Items
    - ....
    - Construction (= Materials + Parts)
    - Tools (Also contains Instruments & Generic Book?)
    - Containers

Again, not a massive priority, and wont be blocking this PR because of it.

**Comment by cosmiccoincidence** [comment]
I'm gonna leave it for now. If we decide we need to change it as we start actually adding things to this folder we can do so then.

**Comment by TimFinucane** [comment]
Oh and could we put Content/Font under art instead? Or is it better under Content?

**Comment by TimFinucane** [comment]
Finished code changes

**Comment by cosmiccoincidence** [comment]
> could we put Content/Font under art instead? Or is it better under Content?

I have no preference on this one, either or is fine by me.

**Review by FaeFinucane — DISMISSED** [review]

**Comment by cosmiccoincidence** [comment]
Conflicts still need to be resolved.

**Comment by cosmiccoincidence** [comment]
Also, can we get a summary if your changes nonanon?

**Review by FaeFinucane — DISMISSED** [review]

**Review by FaeFinucane — APPROVED** [review]

**Review by onebigames — APPROVED** [review]
Let's get this over with

**Pull request merged**
