### PR TITLE
Adding tool belt

### PR DESCRIPTION
**Pull request by stilnat**
# Summary

doc : https://ss3d.gitbook.io/systems/containers/setting-up-a-container/custom-storage-conditions

This PR allows player to wear a toolbelt. The toolbelt can't be put on without a jumpsuit, and the jumpsuit needs a toolbelt to be put on.

#### PR checklist
- [x] The game builds properly without errors.

- [x] No unrelated changes are present.

- [x] No "trash" files are committed.

- [x] Relevant code is documented.

- [ ] Update the related GitBook document, or create a new one if needed.

# Pictures/Videos)

# Testing

Try puttin the belt in its container while not wearing a jumpsuit and while wearing one. Try removing the jumpsuit while wearing a belt and while not wearing one. 

#### Networking checklist

- [x] Works from host in host mode.

- [x] Works from server in server mode.

- [x] Works on server in client mode.

- [x] Works and is syncronized across different clients.

- [x] Is persistent.

# Changes

- Did some changes in the container script. Container now check for a bunch of custom exterior conditions, which are script implementing the IStorageCondition interface on the same game objects as the container. This allow to add custom conditions to fullfil to add and/or remove stuff from a given container.

- Refactored just a bit the container script as I noticed it was a bit messy regarding which method can add or delete things from the list of items in the container and it was causing small bugs like removing the toolbelt from hand if it could not go in the waist container.

- Had to remove the bodypart asset database and put everything in the item one. I realized we can't put the same asset in two different addressable groups, which is an issue for body parts since they can be viewed as items and bodyparts. The best option is to have a single addressable group called "gameObject" which just contain every game object asset we have. not implemented here but it's kind of just renaming the asset database (and fixing eventual errors in code arising from the renaming)

# Known issue

- Seems like the belt onclient sometimes freeze mid air, I've no idea why this happen with this particular item. Might have to do with the belt topology and position, which makes it collide weirdly with the player. A solution could be to put the belt container slightly in front of the player so when it gets out it doesn't collide weirdly. It doesn't really happen on host though so not sure this is why.

# TODO

- [x]  small refactor of the container script to have all logic regarding adding and removing items in their respective method. (includes setting up properly container upon adding removal and the rest)

### CODE REVIEW

**Review by cosmiccoincidence — COMMENTED** [review]
- The Backpack and Toolbelt should be moved into the WorldObjects/Items/Clothes/ folder.
- And said folder should actually be renamed to "Clothing" to match our other folder structures.
These can be done in this PR or a follow-up hotfix PR, your choice.

**Review by cosmiccoincidence — CHANGES_REQUESTED** [review]
- The UI inventory slot for the belt is the same size as the hands ui but it should be the same as the backpack/id/pockets slots.
- Was Toolbelt added to the asset data system? It doesn't show up when searching for it in the tilemap menu.
- Trying to remove the jumpsuit when a toolbelt is worn causes the jumpsuit to bug out. See below:
https://github.com/RE-SS3D/SS3D/assets/41941008/958c3d84-3ac6-45d1-a979-cca541f3ff90
- Inventory slots rearrange upon creating a new round: https://streamable.com/km9qoi

**Review by cosmiccoincidence — COMMENTED** [review]
Um... Not sure what just happened but after making my review review, I noticed github desktop was telling me there were commits to pull so I pulled them and reviewed again to make sure I'm reviewing the latest work.... and well...
https://streamable.com/jtgmxw

**Comment by stilnat** [comment]
@cosmiccoincidence inventory slots rearranging is a bug on develop already, made an issue for it. The rest is hopefully fixed. Lmk

**Review by cosmiccoincidence — CHANGES_REQUESTED** [review]
You didn't remove the Toolbelt prefab from the old location.

**Comment by stilnat** [comment]
@cosmiccoincidence oops, toolbelt removed.

**Comment by cosmiccoincidence** [comment]
> @cosmiccoincidence oops, toolbelt removed.

Same with backpack please... you didnt remove the old one (/Items/Functional/Storage/Objects/)

**Review by cosmiccoincidence — CHANGES_REQUESTED** [review]
Jumpsuit still bugs out when trying to drag it to hands. The inventory icon disappears.

https://github.com/RE-SS3D/SS3D/assets/41941008/129c47ab-ddb6-4af8-a921-c42e215056ef

**Review by cosmiccoincidence — CHANGES_REQUESTED** [review]
Looks good. Waiting on gitbook doc.

**Comment by stilnat** [comment]
doc added : https://ss3d.gitbook.io/systems/containers/setting-up-a-container/custom-storage-conditions

**Review by cosmiccoincidence — APPROVED** [review]
https://ss3d.gitbook.io/systems/containers/setting-up-a-container/custom-storage-conditions

**Pull request merged**
