### PR TITLE
Background art for main menu

### PR DESCRIPTION
**Pull request by Eddyskingdom**

### CODE REVIEW

**Comment by Eddyskingdom** [comment]
@joaoburatto fixt

**Comment by cosmiccoincidence** [comment]
https://1drv.ms/u/s!AkL13ubt2eYmyrFnb6sId_QFkLE3Tg

**Comment by cosmiccoincidence** [comment]
Updated the lobby image. But it seems we are still debating on this some...

Preferably to complete #279 the background should remain in view until the player enters the server not just until the player clicks host/embark. As it is right now, the player hits host then can see the map for 3 seconds or so while it loads then joins. Preferably the player never see the map until they actually join.

**Comment by Eddyskingdom** [comment]
going to close this and open a new PR with the work of the overhaul

**Pull request closed without merging**
