### PR TITLE
Change a bit how the builds folder is organized

### PR DESCRIPTION
**Pull request by joaoburatto**
## Summary

Moves some stuff around and updates files.

### CODE REVIEW

**Review by stilnat — DISMISSED** [review]
Please write something in BUILD THE GAME HERE so people are not confused about it. Just explain it's a placeholder if it's what it is.

**Comment by cosmiccoincidence** [comment]
> Please write something in BUILD THE GAME HERE so people are not confused about it. Just explain it's a placeholder if it's what it is.

Alternatively, explain it in the builds readme.

"Build the project to the Game folder inside this folder."

**Review by cosmiccoincidence — CHANGES_REQUESTED** [review]
Rename all files to PascalCase. The README.txt can be exempt from renaming.

We should probably add some info about project building to the gitbook too.

**Comment by joaoburatto** [comment]
> Rename all files to PascalCase. The README.txt can be exempt from renaming.
> 
> We should probably add some info about project building to the gitbook too.

Can we leave that for later? It would break a few things

**Review by cosmiccoincidence — APPROVED** [review]
I was too lazy to test this but based on the small amount of changes I'm going to assume it's fine.

**Comment by Ryan089** [comment]
> I was too lazy to test this but based on the small amount of changes I'm going to assume it's fine.

SS3D quality control at its finest.

**Pull request merged**
