### PR TITLE
add test runner workflow for each commit

### PR DESCRIPTION
**Pull request by Em3rgencyLT**
* Create test runner workflow
* Add discord webhook secret (done by @cosmiccoincidence)

## Summary

This will execute all the edit and play mode tests within the project on every commit ~and pull request~. The results will be displayed within github actions. ~Ideally we'd have a discord bot post in the git-log channel when tests fail to make everyone aware, but that needs to be done separately from this.~ When a test execution fails, a discord message will also be displayed to let everyone know.

The discord message feature requires a new secret to be added to github, which @cosmiccoincidence has already done.

Actions executed by this workflow:
1. Clone the repository
2. Execute Edit and Play mode tests
3. Send discord message if tests fail
4. Upload test results as an artifact for reviewing

## Pictures/Videos
New workflow listed as Run Tests. If a test fails it marks the entire action as failed.
tests1

Actions performed
tests7

Results view on a success
tests3

Quick summary when looking at a run with failures
tests4

Detailed test results on a failed run
tests5

Discord message on a failed run
tests6

### CODE REVIEW

**Comment by stilnat** [comment]
I got a nerd orgasm. For real I wasn't even aware that this was something we could do. It's exciting stuff. I'll check tomorrow in more detail.

**Comment by Ryan089** [comment]
Does this prevent merging when tests fail, or just notify the reviewer?

**Comment by Em3rgencyLT** [comment]
@Ryan089 As you can see by the big fat "Merging is blocked" it does prevent merging :D

There seems to be an issue reading the license for the test runner on this repo, so its failing. I'm having a hard time debugging it, as it runs without issues on my repo. @stilnat could you push a tag to some branch to test the release workflow if that still works? Not sure if this is feature specific or a wider issue with the license.

**Comment by Em3rgencyLT** [comment]
I'm really hoping the release build also fails, as that would indicate a license issue. Maybe its something silly like someone accidentally clicked "update" on an empty input field and deleted it :D That would be an easy fix.

**Comment by Em3rgencyLT** [comment]
Figured it out. This isn't supposed to work while on a PR, as github does not pass secrets to actions triggered by forks for security reasons. 
Screenshot_20211228_032501_com duckduckgo mobile android

Will remove the pull request activator tomorrow and only leave it on commits.

**Comment by Ryan089** [comment]
I did notice the "Merging is blocked" statement. Right under it is "Merging can be performed automatically with 1 approving review". So the question still stands: does this prevent merging completely while tests are failing, or can a reviewer approve and merge PR's despite the presence of failing tests?

**Comment by Em3rgencyLT** [comment]
Updated PR, to only run tests on commit. Additionally, it will also send a message to discord now if the test run fails!

@Ryan089 as I understand it, all merge checks have to pass before merging is allowed. Of course people with access can ignore merge checks, either manually or by simply removing them. So there is no 100% way to stop merging if someone with enough permissions wants to merge.

Either way, to answer your question now, no, this will not prevent merging. As we can no longer run the tests on the PR itself, only on the commit once it is merged. We could only run it on the PRs if all contributors were part of the main repository and committed to it directly. But since we have to use forks, it is a security measure to prevent fork action runners from accessing the secret keys stored in the main repository. And this workflow needs the github license and discord webhook secret keys.

**Review by stilnat — APPROVED** [review]
Nice to have test executed on each commit !

**Pull request merged**
