### PR TITLE
[WIP] Add health system

### LINKED ISSUE #165: Basic health and damage
### Summary

Reimplement the health and damage system that was originally implemented in #92 before our interaction system overhaul.

### PR DESCRIPTION
**Pull request by henkhooft**
## Summary
This PR adds a health system with support for multiple systems. Humans and other creatures can now have the following:

---------------------------------------------------------
**Health status**
You can now receive Brute, Burn, Toxic and Suffocation damage. Receive too much damage and you loose will your consciousness. Death will follow soon after (only ragdolls you for now).

**Bodyparts**
Each body part can be damaged individually and starts bleeding after a while. The body part will be severed if too much damage is received. Unfortunately you cannot put body parts back on as of yet.

**Brain system**
 Humans can now get brain damage, but luckily right now it does not affect your mental state yet. The code also supports brain infections to occur.

**Blood system**
Each creature now has a blood system with a heart rate. The rate of the heart beating also determines the update rate. At initialization each creature receives a unique DNA string and a blood type is assigned based on a RNG. You can die now if you loose too much blood.

**Respiratory system**
Each creature can now breath via a respiratory system. If there is not enough oxygen or too much CO2, you will slowly suffocate. You will also receive damage if the pressure is either too high (above 550 kPa) or too low (below 16 kPA oxygen). Breathing air will use oxygen and generate CO2. How much you breath is dependant on your heart rate.

**Metabolism system**
Creatures have a nutrition level and you can starve to death after a while. Being in starving mode gives a debuff so that you cannot run anymore. There is support for metabolism effects as well, so being poisoned is supported right of the bat.

---------------------------------------------------------
**Integrity system**
Objects can now have health as well. Each object which contains the integrity component has 100% integrity which decreases as you damage it. Armor and resistances can be applied as well to reduce or make it immune to certain damage. 

**Logger**
A proper logger is implemented that allows messages to be linked to a category (e.g. health, tilemap).

---------------------------------------------------------
## Work in Progress

- [x] Get proper colliders on human model

- [x] Integrate severed body parts with new health code

- [ ] Implement bleeding effect

- [ ] Get multiplayer health sync working

- [x] Implement basic health UI

- [ ] Do file clean up

## Pictures/Videos
afbeelding

_More will follow..._

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
It would be nice if you could remove any unneeded leftovers from our old health system in this PR also.

**Comment by joaoburatto** [comment]
Also please make you die if you have your head severed, you should be ragdolled if that happens.

**Comment by DoomsdayOrange** [comment]
Receiving too much damage shouldn't kill you automatically. The health system should be all tied to the brain and its health.

For example, getting shot multiple times in the gut shouldn't kill you because your brute damage was too high, it should kill you because of blood loss which starts to damage your brain and kill it. People can easily keep running for miles after getting shot multiple times until their brain taps out from a lack of blood, Adrenaline is hell of a drug.

Same can be said about burn and toxic damage. You dont die *just* because youre covered in 3rd degree burns. You die because of shock, blood loss, infection, and organ failure. All of these can cripple a persons system and cause complications that lead to the brain dying along with the person.

**Comment by DoomsdayOrange** [comment]
Another thing, a pain system should be introduced, with drugs or natural bodily functions regulating it. For example, as taken from Wikipedia; "Extreme pain causes neurogenic shock by overexciting the parasympathetic nervous system. This results in a significant decrease in heart rate (Bradycardia); which in turn decreases the pulse and leads to a dangerous drop in blood pressure [shock]."

I highly recommend you @ LarjLad on the server. He's a good friend of mine and he's an EMT. He has way more knowledge on the human body than me. I recommend you work alongside with him on this PR.

**Comment by cosmiccoincidence** [comment]
Closing this for now and marking it derelict.

**Pull request closed without merging**
