### PR TITLE
Reimport connectables

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
# Summary

Reimports connectable models. Ensures that they are all rotated correctly upon import/export.

## Fixes

- Rotations for connectables.
- Mesh naming.
- Booth O model off-centered.
- Reduced plenum vertices.
- Removes outdated wall panels (they are backed up on art repo).

### TODO

- [x] Rotate all connectables in blender (around world cursor). Apply rotations. Export fbxs using correct settings.
- [ ] ~~Redocument connectables design. Correct shape descriptions and take new screenshots.~~
- [x] Import new fbxs in Unity. Fix scripts and prefabs.

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Don't merge this yet. Need to double check something first. 

(Ready now)

**Review by stilnat — CHANGES_REQUESTED** [review]
trying to use the dropdown of the tilemap menu returns some exceptions, check the tilemap
menu references in inspector are all set correctly.
```

NullReferenceException: Object reference not set to an instance of an object
AssetGrid.LoadObjectGrid (SS3D.Systems.Tile.TileLayer[] allowedLayers, System.Boolean isItems) (at Assets/Scripts/SS3D/Systems/Tile/TileMapCreator/AssetGrid.cs:84)
```

**Comment by cosmiccoincidence** [comment]
> trying to use the dropdown of the tilemap menu returns some exceptions, check the tilemap menu references in inspector are all set correctly.

Please try again now that I merged in upstream.

**Comment by stilnat** [comment]
Messing with the mesh rotations in the .fbx does that, because the connectables scripts relies on the original rotation of meshes. Menu fixed.
image

**Comment by cosmiccoincidence** [comment]
> Messing with the mesh rotations in the .fbx does that, because the connectables scripts relies on the original rotation of meshes.

Ok so this is a script issue. We have gone thru this model rotation issue back and forth a couple times... and in the process have had to invert the connection scripts a couple times as well. I'll try to invert them again.

**Comment by cosmiccoincidence** [comment]
@stilnat I made a temporary fix in the scripts.

The issue is caused by the tilemap connectable system being oriented with north being what we are now calling south. Before we turned around the export settings it was fine. I knew this issue would arise... The connectables have since we exported with the "correct" rotational settings but they are now rotated in a way that breaks connections as you noted. This can be resolved by inverting some of the code in their scripts. The problem here is that the code is kinda backwards in some instances, one example is how all the scripts say "U" shape connects to the south, yet in the design document it says north.

So the long-term solution here is to physically rotate all the connectables in blender, use the new export rotation settings, redocument the connectable design so the shape descriptions are correct and even take new photos, then finally fix the scripts for any rotational mishaps all that brings...

I guess I'll put this on WIP and slowly work thru that process.

**Comment by stilnat** [comment]
@cosmiccoincidence what you describe should work, hope it's the last time we have to do something like this though.

**Comment by cosmiccoincidence** [comment]
Ok, so it seems I didn't have to update the documentation much or take any new images for 
it because I rotated everything in blender around the world origin and the objects didn't lose orientation from one another. And none of my screenshots in the documentation included the world arrows so there shouldn't be *much* confusion.

**Review by stilnat — APPROVED** [review]
works well

**Pull request merged**
