### PR TITLE
Make airlocks move

### LINKED ISSUE #1316: Import airlocks opening and closing
## Summary

import from outdated airlocks closing and opening, it should work in a similar fashion, except for sound, sound needs an issue on its own.

### PR DESCRIPTION
**Pull request by stilnat**
# Summary

Airlocks are back ! Airlocks open and close upon a player getting close to one. See the video below.
No sound for now, we need before a proper audio system to be set up. The one from outdated looks good to me, except turn the singleton into a "System"

credits to  @DooblyNoobly  for the original PR #137

doc : https://ss3d.gitbook.io/dev-guide/guides/working-with-animations
https://ss3d.gitbook.io/design/environment/tilemaps/tile-objects/airlocks

#### PR checklist
- [x] The game builds properly without errors.

- [x] No unrelated changes are present.

- [x] No "trash" files are committed.

- [x] Relevant code is documented.

- [x] Update the related GitBook document, or create a new one if needed.

# Pictures/Videos)

https://github.com/RE-SS3D/SS3D/assets/14344825/536db383-1fcc-4d90-94f8-8101b61b2b61

# Testing

Go close to a civilian airlock, see the magic.

#### Networking checklist

- [x] Works from host in host mode.

- [x] Works from server in server mode.

- [x] Works on server in client mode.

- [x] Works and is syncronized across different clients.

- [x] Is persistent.

# Changes

- Compared to outdated, a major change is the removal of animation events, and using State machine behaviours to get events when the animator gets from one state to another. It won't break if we change the animations for the airlock. It should be a standard to use SMBs instead of animation events, it's just more solid and easier to debug too.

- Made some changes on the airlock prefab, some renaming so the animations work properly. Let me know if it's an issue and if we should do new animations instead.

# Known issues

- I took the animations from outdated and had to rename right door to left door and left door to right door to make the animation works properly. Otherwise it was "inverted" (doors going inside each other when opening). Not sure how to deal with that properly.

- in Editor, end of door closing up look not that great. It doesn't occur in build. Don't know how to solve that.

# TODO

- [x] Maybe add some instructions on gitbook on dealing with animations events from now on, using Mecanim's events instead of the legacy ones.
- [x] Document everything
- [x] Check that only entity layer can activate doors
- [x] Check if all the right materials colors are changed.
- [x] Check the behaviour with multiple players going close to it.
- [x] Move the state behaviour script in furniture system
- [x] Put back left and right correctly

# Related issues/PRs 

close #1316

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
File conflicts. Please merge in master.

**Comment by stilnat** [comment]
> File conflicts. Please merge in master.

Done

**Comment by cosmiccoincidence** [comment]
> I took the animations from outdated and had to rename right door to left door and left door to right door to make the animation works properly.

It shouldn't be very difficult to swap the animations around so that we can have the objects named correctly. (just swap the values on the left at each point marked on the timeline) (Also you can turn the blend shapes on and off on the panel via the animation panel)

image

**Comment by stilnat** [comment]
@cosmiccoincidence good take on the animation. Regarding blend shape, I'm doing that programatically currently, are you fine with that ?

**Review by cosmiccoincidence — CHANGES_REQUESTED** [review]
Add new functionality to the SecurityAirlock.prefab as well please, since it is now on the new map.

**Comment by stilnat** [comment]
@cosmiccoincidence security airlocks updated

**Review by cosmiccoincidence — APPROVED** [review]
I didn't test this since before the security door fix, but I'll take your word it's good.

**Pull request merged**
