### PR TITLE
Turn Systems into Prefabs

### LINKED ISSUE #1166: Turns the Subsystems into prefabs
## Summary

simply turns the Systems and Lobby Subsystems into prefabs, to prevent unnecessary merge conflicts whenever someone changes the settings of a System or adds a new one into the game

Changes the Lobby scene by turning both System game objects into Prefabs

See #1110 for references, but for some reasons we had some unsolvable issues with it.

### PR DESCRIPTION
**Pull request by Ryan089**
## Summary

Created a bunch of prefabs for Systems, in lieu of having them as scene objects. Nil content changes.

## Fixes

Closes #1166

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
I'd go with a different name for the "Prefabs" folder. There are other types of prefabs so the name isn't very clear. I'd change to "Lobby" or something.

**Comment by Ryan089** [comment]
> 

@cosmiccoincidence Renamed as requested.

**Comment by cosmiccoincidence** [comment]
I haven't play tested it. Gonna let @RE-SS3D/game-maintainers handle it.

**Review by stilnat — DISMISSED** [review]
Works fine on my side, I'd just like play tests to be merged first if no one mind.

**Review by joaoburatto — APPROVED** [review]

**Pull request merged**
