### PR TITLE
Add generic models

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
# Summary

Add some more generic models for various purposes:
- Airlock Floor Tile
- Slot Machine
- Water & Fuel Tank
- Glass Shard
- Glass Sheet
- Glass Reinforced Sheet
- Steel Rod
- Wood Log
- Wood Plank
- Welder
- O2 air tank
- Plasma air tank

Adds missing item SOs for:
- FloorTile
- Boombox

Adds examine data files for all objects added in this PR.

### CODE REVIEW

**Review by stilnat — DISMISSED** [review]
seems all good to me ! just need to fix the little conflicts

**Comment by cosmiccoincidence** [comment]
The jumpsuit is now missing from the player at round start. Not sure how to fix that.

**Comment by stilnat** [comment]
conflicts to solve before review

**Comment by cosmiccoincidence** [comment]
PR has been failing checks since I added the jumpsuit items.

**Review by stilnat — APPROVED** [review]
no issue found, models properly set up

**Pull request merged**
