### PR TITLE
Adds a Mini Scene

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
### Summary

- Adds a mini scene as an alternative to the main scene. The purpose of the mini scene is for a temporary work around for issue #314. This smaller scene doesn't fail for connecting clients. (The mini scene is the same and main scene but is missing the maintenance, hallway and some items)

- Also removes some left over .meta files from the recent asset retraction.

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Added High Priority label because this will allow for proper network testing for other PRs.

**Comment by Alainx277** [comment]
Not needed to test other networking. Testing on an unrealistically small scene is not going to help the project.

**Comment by cosmiccoincidence** [comment]
I re-opened this PR simply to still remove the left-over .meta files from the recent asset retraction.

I removed the mini scene now.

**Comment by cosmiccoincidence** [comment]
Actually Ill just remake the PR for less confusion.

**Pull request closed without merging**
