### PR TITLE
Update PosterVertical.prefab

### LINKED ISSUE #1357: Placing vertical poster fails
## Summary

Trying to place the vertical poster on a wall via the build menu fails.

## Current Behavior

When you try to place the poster it pops of the wall as if it encountered collision and it bugs out the tilemap menu until you restart the game.

## Steps to Reproduce

Try to place a vertical poster (wallmount) via the build menu.

### PR DESCRIPTION
**Pull request by Sjerty**
# Summary
Fixed vertical poster sticking out of a wall and drop when placed

#### PR checklist
- [x] The game builds properly without errors.

- [x] No unrelated changes are present.

- [x] No "trash" files are committed.

# Testing
Try placing VerticalPoster from builder menu

# Video
https://www.youtube.com/watch?v=uOvFyq5iz6Q

#### Networking checklist

- [x] Works from host in host mode.

- [x] Works from server in server mode.

- [x] Works on server in client mode.

- [x] Works and is syncronized across different clients.

Don't quite understand how to check this, because when I close game window and reconnect as a client it won't return me in game, just leave me in the lobby?
But if I join as new client everything is okay
- [x] Is persistent.

# Changes
PosterVertical.prefab - removed it's rigidBody and added a networkObject script so it would update on a client side

# Related issues/PRs 
Closes #1357

### CODE REVIEW

**Comment by stilnat** [comment]
@Sjerty Thanks for your work, and welcome to SS3D. I'll check your PR very soon. To answer your question, don't worry too much about this one. disconnecting and reconnecting is currently pretty broken. If it works on client and host at first launch it's all that matters for now.

**Comment by Sjerty** [comment]
@stilnat Got it. Thanks for a quick reply!  I'm still learning unity and all new stuff that comes with SS3D, but I do have some programmer experience, so I hope one day I'll contribute with something more significant C:

**Review by stilnat — APPROVED** [review]
good work, also thanks for the video, makes review faster. Approved ! You are Sjerty on discord too right ? Need to know cause we can add you as a contributor now.

**Comment by Sjerty** [comment]
@stilnat Yes, I'm also "Sjerty" in a discord server, the one with "1000 yard stare cat" profile picture :p

**Pull request merged**
