### PR TITLE
Fix issues with basic Substance system

### LINKED ISSUE #542: Booze Dispenser Broken
### Summary

Seems the booze dispenser is no longer working...

### Steps to Reproduce

Try filling up a cup or beaker from the booze dispenser... nothing shows up in the interaction menu when right clicking it, nothing happens. The water cooler works fine though.

The prefab itself is busted, seems like it doesn't like multiple instances of the substance dispenser script...
image

### LINKED ISSUE #725: Substance Dispenser Not Working Properly
## Summary

It seems that the 'fill' interaction which dispenses substances (which is present on the boose dispenser and the water cooler) is not working.

## Current Behavior

Grabbing a cup and using the fill interaction doesn't seem to fill the cup, at least not visually.. I tried spamming the fill interaction to see if it stopped at some point indicating the cup is full but that didn't work for me either.

## Steps to Reproduce

- Go to the water cooler and use the dispense cup interaction to get a cup
- Right-click the water cooler (a fill interaction should appear but it doesnt)
- Right-click the booze dispenser in the kitchen for the fill interaction to appear and try using it... nothing seems to happen.

## Expected Behavior

It used to dispense the substance in the cup and fill it visually. It broke at some point.

## Context

Original implementation: https://github.com/RE-SS3D/SS3D/pull/358

Related to #542

### PR DESCRIPTION
**Pull request by Ryan089**
## Summary

Fixes a couple of longstanding bugs with the basic substance system.

Substance Dispensers can now toggle between dispensing an amount in milliliters (good for drinks) or moles (good for chemistry). All calculations etc remain in moles. Booze dispensers offer a range of beverages, dispensing 30mL each time. Water coolers will fill the 300mL paper cup in a single interaction. The substance display has been partially fixed.

## Pictures/Videos

Substances

## Changes to Files

MiniStation was changed to add the booze dispenser, water cooler and some beakers for testing. The most critical change was adding the Registry gameobject (holding the SubstanceRegistry script) back into the scene.

## Technical Notes

- SubstanceDisplay passes more data to the client via the Remote Procedure Call, so liquids in beakers now appear on the client that same as they do for the server.

- Large and Small Beakers now have colliders again, so they no longer plummet for eternity under gravity.

- The SubstanceRegistry is needed in the scene for any substance interactions - I believe the absence of this was the root cause of the water cooler failing.

- The SubstanceContainer.CanTransfer() function was the root cause of the Booze Dispenser failing - it was incorrectly returning that you could only transfer substances if the container was locked (rather than if it wasn't locked).

## Known issues

Substance Display and the corresponding shader are semi-functioning again, but probably require more development in #766.

## Fixes

Closes #725
Closes #542

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Ministation was recently changed (I believe in the container rework). You will likely need to update you file then re-add your changes to it.

**Comment by Ryan089** [comment]
> Ministation was recently changed (I believe in the container rework). You will likely need to update you file then re-add your changes to it.

No worries. It is also changed in the Mirror update, so I will WIP this one until Mirror update is merged, then re-do the key changes in MiniStation.

**Comment by Ryan089** [comment]
Ready for review.

**Review by stilnat — CHANGES_REQUESTED** [review]
Sorry Ryan for the delay, work is crazy right now. So I messed around with the client, and the client can still fill up the beaker over the max amount, or at least the interaction still appear. It works great for the host though. If you could solve the issue with the client, we'll be all good for this PR !

**Review by stilnat — CHANGES_REQUESTED** [review]
Great, everything's solved ! Since RecalculateAndSyncVolume is going to be a server only method, could you please add a [server] tag ? I'd like to start picking up good habits on this, it'll help when we'll work on separating server and client code.

**Review by stilnat — APPROVED** [review]
Great job ! Everything's working as expected and the code is clear. Thank you Ryan :)

**Pull request merged**
