### PR TITLE
Pause menu

### PR DESCRIPTION
**Pull request by joaoburatto**
### Summary

Adds a little pause menu to the game.

## Pictures/Videos (optional)

image

## Changes to Files (optional)

This changes the main canvas prefab, and some hierarchy inside it.

## Technical Notes (optional)

There's a pause menu script that handles the menu animator, and I modified a little the network manager script to only spawn a new round manager (now pause menu) if there's isn't one.

## Known issues (optional)

Disconnecting does not make you go to a main screen or something, we will need the character customization thing for that first, which will be happening soon if everything goes right.

### CODE REVIEW

**Comment by DoomsdayOrange** [comment]
Getting warnings in the console: Prefab 'PauseMenu' has multiple NetworkIdentity components. There should only be one NetworkIdentity on a prefab, and it must be on the root object.

I also have this random issue where the character freezes in place while still playing his movement animation. Not sure if its related to this PR or not.

**Comment by DoomsdayOrange** [comment]
More of an aesthetic critique; there is too much time passing between clicking resume and the pause menu actually going away, The same happens with just hitting esc again, but less time passes.

**Review by Dennis-Nesterenko — CHANGES_REQUESTED** [review]
Lessen the amount of time between clicking resume and the menu going away, same with hitting escape.

**Review by Dennis-Nesterenko — DISMISSED** [review]
Not sure if intentional: 

"Prefab 'PauseMenu' has multiple NetworkIdentity components. There should only be one NetworkIdentity on a prefab, and it must be on the root object."

**Comment by henkhooft** [comment]
Menu works pretty smooth. However one significant issue that I found is that that clients cannot connect to the server anymore.

**Review by henkhooft — DISMISSED** [review]
Works as it should be now. Good work!

**Review by cosmiccoincidence — APPROVED** [review]

**Pull request merged**
