### PR TITLE
Move IngameDebugConsole folder to External

### LINKED ISSUE #1154: Move IngameDebugConsole folder in Scripts/External folder
## Summary

The assets in this folder allows us to have a debug console like Unity console in builds. when moving the folder, check that it doesn't break our in build console.

### PR DESCRIPTION
**Pull request by iamteapot422**
closes #1154

### CODE REVIEW

**Comment by joaoburatto** [comment]
@Mechar418 why did you commit these files?
image

**Comment by iamteapot422** [comment]
@joaoburatto accidentaly, i cant git ignore them for some reason

**Comment by joaoburatto** [comment]
@Mechar418 just reset the files to what they were before. You can ignore by not commiting them. Doesn't matter if it auto generates everytime for you. Only committed files will show here

**Comment by iamteapot422** [comment]
@joaoburatto done

**Comment by joaoburatto** [comment]
Nice! Will test later.

**Comment by iamteapot422** [comment]
@joaoburatto whats up?

**Review by TaylorNAlbarnaz — APPROVED** [review]

**Pull request merged**
