### PR TITLE
Tilemap construction

### PR DESCRIPTION
**Pull request by TimFinucane**
Adds networking of tilemaps to clients, and ability to construct/deconstruct walls with the crowbar, and construct/deconstruct tables with the wrench.
Fixes #123

[Video demonstration](http://s1.webmshare.com/Qe0ja.webm)

Edits:
- There seems to be quite a few edits to the scene. The only thing i meant to add was the wrench.
- Edits to wall, floor, and crowbar prefabs to add the given interactions
- Deletion of looots of unused tilemap prefabs from the old system.

Current problems:
- The script attached to the player to call commands to the tilemap just feels wrong to me. I have an idea about how to fix it but it involves the interaction system
- Because the interaction system fires all events at once, constructing a table or wall will also drop the object in hand. Again, this is the interaction system not the tile system so i didn't solve it here.

### CODE REVIEW

**Comment by Dyhr** [comment]
Why can you drop the crowbar on the walls in the first place?

**Comment by TimFinucane** [comment]
Because the tile from which the wall is constructed is also a PlaceableSurface, meaning the Place action occurs as well as the ConstructWall action

**Comment by Dyhr** [comment]
How about we just make floors have `PlaceableSurface`? Or follow SS13 and have it on any tiles?

**Comment by TimFinucane** [comment]
The floors do have PlaceableSurface. A floor has both PlaceableSurface and ConstructableWall, and both get called.

**Comment by TimFinucane** [comment]
Oh also did notice, worryingly enough, that if the server adds a wall that does not get communicated to a client (so the server sees a wall and the client does not), then the server will not be worried if the client walks through that wall.
It seems mirror doesn't care because the walls don't have a net id. Which is a pain.

**Comment by Dyhr** [comment]
Ah, sorry, I misunderstood. I would still suggest not having it on the floor

**Comment by TimFinucane** [comment]
I'd like it to be on the under-floor object once those are in the tilesystem, but they aren't yet.
Where would you suggest it go?

**Pull request merged**
