### PR TITLE
Clean Up some UI files

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
## Summary

Cleans up *some* of the files in /Art/UI/.

## Changes to Files

- Combines/sorts the 'Storage' & 'Inventory' folders and renames some interior files to PascalCase.
- Renamed the `Rendered Icons` folder and interior files to PascalCase.

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Waiting for #1051 to be merged first and then I will update this pr from upstream,

**Comment by joaoburatto** [comment]
LGTM

**Review by joaoburatto — DISMISSED** [review]

**Comment by cosmiccoincidence** [comment]
Still not ready to merge yet. Need to update from upstream and resolve conflicts first.

**Comment by cosmiccoincidence** [comment]
Should be ready for re-review now.

**Review by joaoburatto — APPROVED** [review]

**Pull request merged**
