### PR TITLE
Clean up Art/Textures

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
## Summary

Cleans up /Art/Textures/ and similar folders.

- Sorts the current files in the Textures folder.
- Moves the Render folder into the Textures folder.
- Renames several files using PascalCase.
- Moves a Unity colors files to the Content/World folder.

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Broke everything again

**Comment by cosmiccoincidence** [comment]
Might be fixed, someone test it pls.

**Review by stilnat — DISMISSED** [review]
wait for #995 before merge.

**Comment by cosmiccoincidence** [comment]
Wait for #1021 to merge first!

**Review by TaylorNAlbarnaz — APPROVED** [review]
Small changes, compreensive and don't break anything

**Pull request merged**
