### PR TITLE
Update mirror version

### PR DESCRIPTION
**Pull request by Alainx277**
### Summary

Updates mirror to the latest release.
Adds the ability to allow anyone to call cmds and have custom logic handling the calling player.

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Why move the mirror folder?

**Comment by Alainx277** [comment]
My bad, Unity import moved it.

**Comment by cosmiccoincidence** [comment]
Why does it change so many files?

**Comment by Alainx277** [comment]
> Why does it change so many files?

Ask the mirror creators?

**Pull request merged**
