### PR TITLE
Update Unity version and fix errors

### PR DESCRIPTION
**Pull request by joaoburatto**
## Summary

Updates the Unity version from `2021.3.0f1` to `2021.3.15f1`, along with package updates and the CS Framework.

### CODE REVIEW

**Comment by stilnat** [comment]
What are the errors fixed by this PR ? @joaoburatto 
Unless it does fix the current broken things we have (just talking about the recently introduced bugs), I'd like this to not be merged before the fixes.

**Comment by joaoburatto** [comment]
> What are the errors fixed by this PR ? @joaoburatto Unless it does fix the current broken things we have (just talking about the recently introduced bugs), I'd like this to not be merged before the fixes.

Errors that came from the updates.

**Review by cosmiccoincidence — CHANGES_REQUESTED** [review]
Getting some errors when play testing, otherwise looks good.

image

**Comment by joaoburatto** [comment]
> Getting some errors when play testing, otherwise looks good.
> 
> image

Can you test again and see if the errors occur again? If not that's just normal Unity memory trash.

**Review by cosmiccoincidence — APPROVED** [review]
Looks good.

**Pull request merged**
