### PR TITLE
Revert changes, retracting usage rights to these assets

### PR DESCRIPTION
**Pull request by binarysudoku**
## Summary

Removed all assets that are no longer usable as the owner no longer consents to their use in the project

### CODE REVIEW

**Comment by binarysudoku** [comment]
Note: this PR will cause missing references until a replacement prefab is set up for the welder muzzle and the welder hit VFX

**Comment by Alainx277** [comment]
It seems as though our asset license [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) is not revocable. 
Let us know if that is not the case.

**Comment by binarysudoku** [comment]
@Alainx277 in which case I'd appreciate a revert on goodwill, but if you won't respect that then i won't kick up a fuss.

**Comment by Alainx277** [comment]
> in which case I'd appreciate a revert on goodwill

I don't call the shot on that. The team is going to discuss it (might take some time though, lol)

**Comment by binarysudoku** [comment]
> I don't call the shots on that. The team is going to discuss it (might take some time though, lol)

Understandable, thank you for the professional response.

**Pull request merged**
