### PR TITLE
Rename Art & Content Assets 2/2

### LINKED ISSUE #287: Consistent Asset Naming Scheme
### Summary

We need to decide on and enforce a consistent naming scheme for all asset types.

### Goal 

The goal here is so assets of all types are named consistently and in a way that allows them to easily found and organized in a search. Below is the one that has been proposed long ago but was never strictly enforced.

```
Item_Group_Gender(If Applicable)_Variant_Color_Job_Anything extra.
(Colors for things such as hair, eyes, eyebrows, and the like do not have a set color, as they can be recolored in the character editor.)

Some examples:

Jumpsuit_Male_Default_Grey_Detailed

Footwear_Female_Sneakers_Black

PDA_Default_Assistant

Hair_Female_Ponytail


Only use _ never - or .
```

Once a system is decided on, it should be noted in contributing.md and in the style guides.

### LINKED ISSUE #713: Floor Overlay Z-Fighting
image

Z-fighting BAD!

(v0.0.95d)

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
*God have mercy on whoever reviews this...*

### Summary

This PR renames all assets under the 'Art', 'Content', and a few other folders to PascalCase.

Main folders processed:
- [x] /Art/Models/
- [x] /Art/Graphics
- [x] /Content/Furniture/
- [x] /Content/Items/
- [x] /Content/Scenes/Maps/
- [x] /Content/Structures/

## Changes to Files (optional)

Mostly just renaming but also updated and moved many assets. I also reduced some objects down to fewer prefabs (like the botany plants and wire coil item).

I DID NOT update the walls and window models (nor rename them) yet because I will be doing that in another PR when I get done documenting the new wall design.

I DID NOT rename the entities because I will just enforce whichever contributor that works on them next to rename them properly.

## Known issues (optional)

*This will likely cause many file conflicts with any other currently developing branch.*

- Breaks wire connections because I removed T & X wire variants due to them not being needed (these shapes will be created using multiple L variants as they are meant to be separate pieces). Someone will need to expand on the wires connection script in order to make this work, until then I see this issue as being acceptable.

Unity_QTEyoUcNNj

- Fill function on water cooler not working for some reason.

- Light fixture on/off interaction is broken.

## Fixes (optional)

closes #287

### CODE REVIEW

**Review by Ryan089 — COMMENTED** [review]
General gameplay functionality reviewed, and appears to be functioning identically to master branch. Fixtures / airlocks now rotated correctly. I have pushed commits to fix Hydrogel renderer issue, BikeHorn examine text issue, and z-fighting issue with tile overlays. I have not yet addressed issue with on/off functionality for lights. I have not (and will not) address changes in wire connectivity - this is an issue for a future PR.

**Comment by cosmiccoincidence** [comment]
Fixes #713

**Comment by cosmiccoincidence** [comment]
I don't think anyone else wants to review this... and I can't blame them. 

Only thing Seteron mentioned is a tiny change to a model which can be done after this pr...

I say let's get this merged and make the known problems into issues. This pr changes many files and has conflicts with most other changes and shouldn't sit open gathering dust.

**Comment by Ryan089** [comment]
I've given it a once-over, but if there is anything you want me to look at in more detail, please let me know. I confess I did not check every single one of the 750,000 lines changed! The only reason I haven't merged already is because I've put some commits on there, and I don't know if anyone has checked those. If you've checked them and are happy with them, I think we should merge.

**Comment by cosmiccoincidence** [comment]
I review your changes and fixed an error with the overlays again. I think it is time to merge.

**Review by Ryan089 — APPROVED** [review]
Known issues to be addressed separately:
- Wire adjacency connectors
- Interaction with items behind colliders
- Minor modelling and colour changes.

**Pull request merged**
