### PR TITLE
Add EditorConfig file

### PR DESCRIPTION
**Pull request by joaoburatto**
## Summary
This adds an EditorConfig file, to improve our code reviewing process. It highlights the code in your IDE of choice with our rules of syntax and style.

I also added it on our GitBook docs: https://ss3d.gitbook.io/dev-guide/guidelines/the-c-style-guide

### CODE REVIEW

**Review by cosmiccoincidence — COMMENTED** [review]
Can this file go in the project settings folder?

**Comment by stilnat** [comment]
It doesn't seem to to anything on its own, how can I use/test this ? Also is this consistent with our gitbook design guide ?

**Comment by joaoburatto** [comment]
@cosmiccoincidence nope, better to keep it in clear sight

**Comment by joaoburatto** [comment]
@stilnat yes it is according to the code guidelines, enforces it. Read the GitBook page to know how to use

**Comment by stilnat** [comment]
@joaoburatto 

> We recently added an editorConfig  file to automate the code review process, it is a file you can add to  or  and it will apply the formatting and style we use to your analyzers, telling you when something is out of order.

that's all I can find regarding the use of this file

**Comment by stilnat** [comment]
@joaoburatto I can't merge that without understanding how it works, the documentation lacks clarity on this matter.

**Comment by iamteapot422** [comment]
> It doesn't seem to to anything on its own, how can I use/test this ? Also is this consistent with our gitbook design guide ?

Download EditorConfig plugin for your IDE, choose the EditorConfig file and see if it highlight unproper naming

**Comment by stilnat** [comment]
I can't seem to make it work with visual studio, the doc says no plugins necessary for it, but then not sure what to do. It doesn't highlight wrong naming.

**Comment by joaoburatto** [comment]
@stilnat That might be a limitation of your IDE. Can we approve this already? please.

**Comment by stilnat** [comment]
I can't even test it, I can't approve it, but maybe another reviewer can take a look.

**Review by TaylorNAlbarnaz — APPROVED** [review]
Works normally for me with Visual Studio

**Pull request merged**
