### PR TITLE
Upgrade FishNet to 2.6.6

### PR DESCRIPTION
**Pull request by Notterox**
## Summary
FishNet has been upgraded to version 2.6.6. In this project, 11 errors that occur upon first opening have been fixed.

## Changes to Files
Many files have been changed as a result of the package upgrade.

## Known issues
1. The `.sln` and `.csproj` files bundled with the FishNet package were ignored and did not get included in the pull request. It is unclear what consequences this may have.

### CODE REVIEW

**Comment by Notterox** [comment]
BTW, 2.6.6 is not most recent version. Upgrading to 3.0.0 or higher would require solving breaking changes. I could look into it if it's needed.

**Review by TaylorNAlbarnaz — CHANGES_REQUESTED** [review]
"Starting a round with more than one player in the lobby is not currently working"

Sorry, but there is simply no way a PR can be accepted with an issue like that, it has to be either fixed or the PR will have to be closed, we can't merge it and have people working on other features immediately have a broken game

**Comment by Notterox** [comment]
@TaylorNAlbarnaz Well, maybe there is a misunderstanding. I can't start a round with more than one person in the lobby on the "develop" branch either, I get errors. (However, I can "embark" after the round has started.) I checked if there was anything regarding that in Github Issues and didn't find any. So, I decided to mention it in this PR.

Am I the only one who has this issue on "develop" branch?

**Comment by TaylorNAlbarnaz** [comment]
@Notterox 
I see, I didn't have this problem just a few days ago, but i'll check again, though i would advise you to not put it as a "known issue" if it's unrelated to your PR

**Comment by Notterox** [comment]
@TaylorNAlbarnaz Got it. I've removed this line from the PR message. I'll create an issue with steps to reproduce the bug later.

**Comment by Notterox** [comment]
I created an issue https://github.com/RE-SS3D/SS3D/issues/973 regarding the bug that was mentioned. The bug was introduced a week ago.

**Comment by TaylorNAlbarnaz** [comment]
> I created an issue #973 regarding the bug that was mentioned. The bug was introduced a week ago.

I've found what caused this bug, already talked with John about it on Discord, i'll just wait for him to commit the fix and then i'll re-review this

**Comment by TaylorNAlbarnaz** [comment]
@Notterox

**Comment by TaylorNAlbarnaz** [comment]
@Notterox 
> I created an issue #973 regarding the bug that was mentioned. The bug was introduced a week ago.

I've found what caused this bug, already talked with John about it on Discord, i'll just wait for him to commit the fix and then i'll re-review this

**Review by TaylorNAlbarnaz — APPROVED** [review]
errors were unrelated to this PR and have been fixed on #974

**Pull request merged**
