### PR TITLE
Add Light to Microwave (#340)

### LINKED ISSUE #340: Add Light to Microwave
### Summary

Add a light inside the microwave that lights up when on and turns off when finished cooking. (bonus: add an emission material to the microwave itself, that also turns on/off when the light object turns on/off)

### PR DESCRIPTION
**Pull request by mjboth**
### Summary

Changes microwave interior to use Palette05 Emission material, emissions will only be active when microwave is on

Panel light will now be off when microwave is not active

No other light source added other than emission material

Change method names in microwave script file to include new code

Microwave door width extended slightly

## Pictures/Videos (optional)

https://user-images.githubusercontent.com/4644621/113675422-570ba900-9689-11eb-9174-acf0ad0d7a24.mp4

## Changes to Files (optional)

The microwave model was modified to change the material inside the microwave to share the same emission material as the panel light.  Light could also be seen in between the microwave and it's door, so the door was extended slightly to close that gap.

Upon start, the emission material on the microwave will disable emissions until the microwave is turned on.  Then disable emissions again when the microwave has finished running.

## Known issues (optional)

Panel light on microwave will not be illuminated when microwave is not in use as microwave interior and panel light are tied to the same emission material.  I was unable to add a second emission material to the model to keep the interior and panel on separate materials.

## Fixes (optional)

"Fixes #340"

### CODE REVIEW

**Comment by joaoburatto** [comment]
Why not add a light inside? might look a bit better, at first glance I swear I didn't noticed it lighted up lol

**Comment by mjboth** [comment]
Using a lighting source like a point light seems to give an uneven distribution of lighting on the interior since the spherical light needs to be scaled down to fit inside the microwave.

SmallPointLightWithNoEmissions


And we can't scale up the light to fill the entire box cause then the light would be illuminating the exterior to the microwave as well.

PointLightOnOffComparison



Once emissions are on, it seems to drown out any lighting the point light would provide.

## Emissions without Point Light


https://user-images.githubusercontent.com/4644621/113798547-5aeb0a00-9721-11eb-9934-ab28b225b773.mp4



## Emissions with Point Light


https://user-images.githubusercontent.com/4644621/113798571-663e3580-9721-11eb-87f8-1b3f5bb0f9a1.mp4



But on a side note, a spot light could be added to illuminate the area in front of the microwave door and give it a neat glow.

This is not in the PR at the moment but can be added upon request.

## Emissions with Spot Light

https://user-images.githubusercontent.com/4644621/113798830-ec5a7c00-9721-11eb-9f3a-e99ae78350c0.mp4

**Comment by joaoburatto** [comment]
Yeah the light doesn't really look that great, but keep in mind the PostProcessing is absurdly bright, there's a lot to fix in it.
What can be done is use another one of the glass materials, we have three I think, with different opacities.

**Comment by mjboth** [comment]
Spot Light has been added to the PR.

I've put together some clips to show what different glass materials would look like.  Let me know what you prefer.

## Glass Very Opaque (Currently used)

https://user-images.githubusercontent.com/4644621/113954708-5ccbd080-97e8-11eb-8d7f-2f6feda6ccd1.mp4


## Glass

https://user-images.githubusercontent.com/4644621/113954719-62291b00-97e8-11eb-980f-efb070772305.mp4


## Glass Absolutely Opaque

https://user-images.githubusercontent.com/4644621/113954731-66edcf00-97e8-11eb-8b2c-8507f3dc5565.mp4


## Glass Opaque

https://user-images.githubusercontent.com/4644621/113954744-6bb28300-97e8-11eb-9394-d89310fd7e11.mp4

**Comment by cosmiccoincidence** [comment]
I noticed John hasn't replied to this. Sorry about that... I would say go with the Absolutely Opaque one, once that change is made I'll give this another play test and merge it if it's good.

**Comment by mjboth** [comment]
change has been applied

**Comment by cosmiccoincidence** [comment]
> change has been applied

I will review this soon. By the way, @mjboth are you a member of our discord server? If so, what is your username?

**Review by cosmiccoincidence — APPROVED** [review]
Looks good to me. Nice job man. Let me know your discord name still, thanks.

**Comment by mjboth** [comment]
Thanks! You can find me on Discord as "AvnFlu"

**Pull request merged**
