### PR TITLE
Self-assign Issues

### PR DESCRIPTION
**Pull request by Ryan089**
## Summary

Adds ability for a potential contributor to assign themselves to issues, as well as unassign themselves. This issue also removes non-functional AddToRoadmap workflow, which is intended to be replaced in its entirety in a subsequent PR.

To self-assign, the contributor must create a new comment on the issue which includes the words: "Assign me"

To self-unassign, the contributor must create a new comment on the issue which includes the words: "Unassign me"

## Fixes

Contributes to #1112

### CODE REVIEW

**Review by stilnat — CHANGES_REQUESTED** [review]
could you put the addToRoadMap deletion in another PR ? I'm not sure deleting it is the way to go, I still have hope that the action used in this workflow get fixed for the new github projects. It's deactivated right now I believe. Otherwise, great stuff !

**Review by stilnat — APPROVED** [review]
great stuff !

**Comment by joaoburatto** [comment]
Assign me

**Comment by joaoburatto** [comment]
Unassign me

**Pull request merged**
