### PR TITLE
Create a controller that handles all tile networking

### PR DESCRIPTION
**Pull request by TimFinucane**
This is needed so that the sub-objects (which can only be networked SOMETIMES because mirror's fucked) have something to make requests through.

Please note that whilst this makes the code slightly uglier, it is unfortunately the only long-term stable way of doing code with Mirror (if you've done enterprise frontend/backend api systems you'll see them use the same thing).

Scene changes:
- Adds the TileServerManager component to the TileMap object. That's it.

### CODE REVIEW

**Comment by TimFinucane** [comment]
Fixes #191

**Comment by TimFinucane** [comment]
Will they not see the airlock, or will they see the airlock having not performed an animation?

**Comment by cosmiccoincidence** [comment]
they will not see it moving (video included in previous comment)

**Comment by TimFinucane** [comment]
I'd say this is a more general problem with being able to recieve TileMap info before logging in. You'll see on the client that the walls havent connected to eachother yet. This is because the TileMap code hasn't actually been started yet. I feel this is fine really as we haven't even decided if we want to allow the player to see the map before they've logged in.

However, once the player has logged in, they will not see any in-progress animation. This would be a difficult bug to fix for very little value, but if it's ok with you i'd instead just like to fix the case that:

- the door should be correctly displayed as open, if the door was open when the player logs in & spawns into the game

**Comment by TimFinucane** [comment]
Ok actually scratch that. Mirror is so shit I can't make it call code on the server when a client joins, for a specific script. Am requesting that the bug be marked but allowed until we switch networking libraries, given that the functionality is still fine

**Pull request merged**
