### PR TITLE
Connectables Update

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
## Summary

Updates connectable models based on [my new design document](https://docs.google.com/document/d/1ful7_gIJo7e74i9LMQuYMpjZMH2V1aT90mwlrQ0hcgE/edit?usp=sharing).

(I have yet to finish some sections of the document at this time and thus those will not be included in this pr, but will come in the future.)

## Changes to files

1. Updates models and prefabs for:
    - Plenums
    - Steel Walls (Girders, Walls, Windows, & Parts)
    - Cables, Wires
    - Tables
    - Disposal Pipes and Bin

2. Adds models and prefabs for:
    - Carpets
    - Conveyor Belts
    - Counters
    - Modular Seats (Chapel Pew, Diner Booth, & Sofa)

3. Fixed 'T' rotations on the simple and advanced connections scripts (the models got rotated so the script needed to be adjusted too).

4. Corrected the object origin positions on the door frame models and adjusted the door.cs script to match.

5. Removed extra doorframes and furniture from the ministation map.

## Issues

There seems to be a bug causing doubled up doorframes after saving the map.

Some connectables have yet to be modeled/designed and were not added in this pr. They will be worked on in the future. (This includes, vines, blobs, wall panels, and more.)

New tasks will need to be made for creating adjacency connector scripts for the following types of connectables:
- [X] Counters
- [x] Directional
- [x] Disposals
- [x] Wires
- [x] Windows

(Don't worry about these, I'll handle them once this is merged and inquire about suggestions then.)

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Thanks @Ryan089 for fixing the disappearing walls!
I'm about out of free time for the day but I got all the big wall bugs resolved now I think and can finish adding in the last of the connectable models and finish this PR soon.

**Comment by Notterox** [comment]
Hi, I accidentally noticed that `PipeT` is faced in opposite direction. Everything works fine but is it ok to be like this?
image

**Comment by Ryan089** [comment]
Good catch!

**Comment by cosmiccoincidence** [comment]
> Hi, I accidentally noticed that `PipeT` is faced in opposite direction. Everything works fine but is it ok to be like this? ![image]

Sorry I haven't been real active here for the past week or so and missed this comment. Great catch, and no that is indeed a mistake I need to correct, thanks!

**Comment by cosmiccoincidence** [comment]
> Great catch, and no that is indeed a mistake I need to correct, thanks!

Fixed now.

**Comment by stilnat** [comment]
I started reviewing it, everything looks fine for plenums

**Review by stilnat — APPROVED** [review]
Great job @cosmiccoincidence, very solid work as always , all good for me !

**Pull request merged**
