### PR TITLE
Updates Project Documents

### LINKED ISSUE #121: Update docs & issue templates
Issue templates should be reduced to just bug, bug and general task, or bug, general task, and suggestion.

- Update readme to remove references to defunct "develop" branch
- For more in-depth contributing info (including model style guide), people should be referred to website, which is preferred place for up to date contrib info and modelling info.

Any other needed updates to these docs can be commented below.

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
## Purpose
Updates project documents.

## Screenshots
[New README.md](https://cdn.discordapp.com/attachments/668172392715255819/682891160569643008/unknown.png)

## Changes to files
- updated CONTRIBUTING.md and README.md
- renamed StyleGuide folder to Documents
- updated C_SHARP.md
- removed art style guide and pictures relating to it (linked to website now instead)
- added buttons for links on README.md
- changed LICENCE-ASSETS and LICENSE-CODE to .md files and added links to them.
- updated issue and PR templates
- updated Wiki pages last night (not included in this PR) but the home page is still looking pretty sad

## Context
- Fixes #121

### CODE REVIEW

**Comment by TimFinucane** [comment]
Nothing looks too bad, changes are fine. Like the image additions to the README.

**Comment by TimFinucane** [comment]
Oh just noticed one more thing. Technically we use the 'feature' issue to mean a whole feature (like interactions, inventory, etc.) that need to be designed before being coded (notice the about says: 'this is a feature to *design* and implement'). It probably makes more sense to have a 'task' and 'bug' issue template, or something along those lines

**Comment by cosmiccoincidence** [comment]
Changed the template.

**Comment by TimFinucane** [comment]
The template should also be renamed from feature.md to task.md, and what do you think about adding a bug-report.md ?

**Comment by cosmiccoincidence** [comment]
Oops, forgot to rename it. Also, we have a bug.md already.

**Pull request merged**
