### PR TITLE
[WIP] Update Unity and Mirror

### LINKED ISSUE #655: Update Unity to 2019 LTS
### Summary

We're still on like 2019.3.12.... wth... time to update!

### PR DESCRIPTION
**Pull request by Ryan089**
## Summary

Updates Unity to 2019.4.28f1 (2019 LTS), and Mirror to 40.0.9.

## Changes to Files

Entire Mirror library replaced. Certain Mirror files modified with project-specific additions (see commit history for details).

## Known issues

image

A couple of remaining compile-time errors exist, both within LoginNetworkManager class.

1. Error CS0453. My assessment: NetworkMessages (which replaced MessageBase) can no longer be classes. In accordance with Mirror documented deprecations, "NetworkMessage requires structs in all cases - classes no longer supported"

2. Error CS1503. It appears we aren't call NetworkServer and NetworkClient RegisterHandler method properly anymore. I suspect this is due to the same issue of NetworkMessages needing to be structs.

## Fixes

Closes #655

### CODE REVIEW

**Comment by Ryan089** [comment]
I'll keep working at this one, but I am removing the WIP PR to avoid clutter.

**Comment by cosmiccoincidence** [comment]
On the contrary, having a WIP pr open and linked to a related issue is an easy way to indicate to contributors that the issue is already being worked on. Also the point I mentioned before about it how it allows for others to look at it and possibly help.

But I'll let you decide.

**Comment by Ryan089** [comment]
Requesting guidance from @joaoburatto and/or @Seteron. I'm probably as far as I can get without significantly reworking LoginNetworkManager and RoundManager. Issues still persist on the client.

**Comment by Ryan089** [comment]
Withdrawing this for now as I don't want any changes to conflict with tilemap rework. I will reopen once tilemap rework has been completed and merged.

**Pull request closed without merging**
