### PR TITLE
Rework how network settings are loaded

### LINKED ISSUE #1175: Create a Launcher to ease the testing process

### PR DESCRIPTION
**Pull request by joaoburatto**
## Summary

This PR changes how the network settings are loaded. Now they are loaded first throught a JSON file with the settings, and then command line args can override those settings. Those settings are only loaded from the file in built executables.

### CODE REVIEW

**Review by stilnat — COMMENTED** [review]
Looking good code wise to me, not approving yet because I did not test it yet

**Review by stilnat — DISMISSED** [review]
- Put host as default network type
- change default server port or server ports in .bat files.

This PR still need testing, I was not able to understand how to test it, need help @joaoburatto

**Comment by stilnat** [comment]
I'd like this to wait until #1168 is closed to be merged, as I worry that it might break play tests significantly, as they rely on the current way network settings are defined.

**Comment by joaoburatto** [comment]
@stilnat you can review it again, I added a launcher screen when you don't have any command args. Will fix the conflicts in a near future.

**Comment by stilnat** [comment]
@joaoburatto I'll wait for conflicts to be solved before reviewing. What about the two comments I made ?

**Comment by joaoburatto** [comment]
> @joaoburatto I'll wait for conflicts to be solved before reviewing. What about the two comments I made ?

I just fixed them. We can wait for play mode tests.

**Comment by joaoburatto** [comment]
Currently waiting for #1168

**Review by TaylorNAlbarnaz — APPROVED** [review]
lgtm

**Pull request merged**
