### PR TITLE
[WIP] Integrate MySQL and basic character saving

### PR DESCRIPTION
**Pull request by joaoburatto**
### Summary

This PR should add MySQL compatibility so we can have local databases for characters.
It works the same way it does in SS13, each server has their local database to save characters, however should be easy to include this in the API aswell.

### Goal

Make possible to save characters and load them according to the CKEY the user has.
- [x] Add MySQL and dependencies.
- [x] Add basic user saving.
- [x] Add a simple tutorial on how to set up in _**database.sql**_
- [x] Improve SQL syntax
- [ ] Add basic character saving
- [ ] Network Host
- [ ] Network Client
- [ ] Add basic CKEY control, via "command-line arguments".

**How to set up your local MySQL database:**
**1) Download and install MySQL, there's a good full installer on their site.**
   Check if you're downloading everything necessary, MySQL Workbench is great to have so you can check manually your data
   TODO: download link
 **2) Create your database.**
   Open MySQL Workbench and create a new database.
 **3) Run this SQL in a database of name from your choice, because I can't figure out how to run from in-game.**
   TODO: figure out how to run from in-game.
 **4) Go to the Editor, load the Lobby scene, and update the LocalDatabaseManager game object with your data,**
   TODO: make this be in a .txt file and/or inside the game.
 **5) Make sure it connects**
   you can do that with the LocalDatabaseManager's object, there's a function to check that, it should be already automated and you 
   should be able to see it in the Console view(and in the future in an in-game console), double check if necessary.
 **6) Profit.**

## Pictures/Videos (optional)

Local Database (2)

Local Database (3)

image

## Known Issues

Client can't send SQL commands yet

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Adding $45 bounty to this

**Comment by joaoburatto** [comment]
> Adding $45 bounty to this

thanks hun, coincidentally I was planning on continuing this one tomorrow

**Comment by Birlinha** [comment]
**How to Setup My Database**
1. [Download and install MySQL](https://www.mysql.com/)
2. On MySQL Workbench Click on File > New Model, or use CTRL + N to quickly open a New Model
image
3. Inside your new Database, you can now click in File > Import > Reverse Engineer MySQL Create Script
image
4.

**Comment by cosmiccoincidence** [comment]
Closing this for now and marking it Derelict so we come back to it.

**Pull request closed without merging**
