### PR TITLE
Smooth camera movement. Fixes issue #923

### LINKED ISSUE #923: Camera - Smooth transitions
## Summary

Make cameras have a smooth transition on target change. You can find the camera code on CameraFollow.cs

## Goal 

Camera does not simply teleports to new target.

## Acceptance Criteria
- [ ] Camera has to interpolate correctly to new targets.
- [ ] Camera interpolations is configurable

## Dependencies

Depends on #921 but you can work from that branch. You can test camera target changes by doing mind swaps

### PR DESCRIPTION
**Pull request by iamteapot422**
Smooth camera movement, vars renaming and camera rotation fix.
Fixes #923

### CODE REVIEW

**Comment by joaoburatto** [comment]
private variables have the _ prefix, public variables are camel case first letter upper and inside function variables should be camel base lower score with no prefix

**Comment by joaoburatto** [comment]
Works fine. SetTarget should have a bool skipTransition to avoid transitioning when the player spawns, that is a weird behaviour to have.

**Comment by Mechar418** [comment]
> Works fine. SetTarget should have a bool skipTransition to avoid transitioning when the player spawns, that is a weird behaviour to have.

Its because camera

**Comment by iamteapot422** [comment]
> Works fine. SetTarget should have a bool skipTransition to avoid transitioning when the player spawns, that is a weird behaviour to have.

Its because camera already has a target at the start. Do you have any ideas how to fix it without a crutch?

**Comment by cosmiccoincidence** [comment]
Fixes #923

**Pull request merged**
