### PR TITLE
Cleanup, Fixing and Visual Improvements

### PR DESCRIPTION
**Pull request by joaoburatto**
A lot of visual changes to make it more appealing, code fixes and UI fixes.
You no longer spawn white boxes when you right click anywhere.
Removed the old NetworkManagerGUI and added a more appealing.
Fixed the Internal Clothing switched that didn't work.

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Looks like you made a scripts folder...
We recently got rid of the scripts folder and split it up.
Scripts related to the game engine are now in Assets > Engine
Scripts related to the game content are now in Assets > Content
And things that we include are in Assets > Libraries

**Comment by cosmiccoincidence** [comment]
In my first play test, the 'Embark' didn't do anything and put out an error. Hosting worked fine. Embarking, I should probably try with multiplayer which I didn't do yet.

I noticed you removed the server stats and the server timer displays which looks much nicer. My one concern is, there is a bug with the server timer which is going to be a bit more difficult to work on without it displayed.

**Comment by TimFinucane** [comment]
Assets/Scripts should not exist, this code is now in Assets/Content/Code (iirc).

**Comment by cosmiccoincidence** [comment]
The code in Assets > Scripts is a merge error cause he used your UI fix PR has a starting point. The only script in said folder is the camera one. But yes, this should be moved before merge.

**Comment by cosmiccoincidence** [comment]
This PR, if successful, will also:
- close #168 
- close #169 
- close #112

**Comment by TimFinucane** [comment]
I agree with the above points that Cosmic made. I am still going to recommend this PR be merged for the smaller things it adds, but would like @joaoburatto to try and make smaller PRs in the future - this will help us get them merged faster as well as it takes less time to test all the changes and usually results in less conflicts.

**Comment by cosmiccoincidence** [comment]
Seems good to me, nice merge of the login managers. Door lights look good now too.

**Pull request merged**
