### PR TITLE
Move files around

### LINKED ISSUE #1132: Clean up /Scenes
## Summary

Clean up /Scenes

## Goal

- Move `/Assets/Scenes/` folder to `/Assets/Content/Scenes/`
- Rename as files to PascalCase if needed/possible without breaking anything.

## Context

~~I'm too lazy to open Unity today~~

https://ss3d.gitbook.io/programming/guidelines/file-naming-and-organization/file-organization

### LINKED ISSUE #1134: Clean up content systems
## Summary

Clean up content systems.

## Goal

- Move the "Input", "UI", & "Substances" folders located in `/Assets/Content/` to a new folder `/Assets/Content/Systems/`

## Context

~~I'm too lazy to open Unity today~~

https://ss3d.gitbook.io/programming/guidelines/file-naming-and-organization/file-organization

### PR DESCRIPTION
**Pull request by iamteapot422**
Closes #1132 
Closes #1134 
Moves InputSystem.inputsettings.asset to Assets/Settings

### CODE REVIEW

**Review by stilnat — CHANGES_REQUESTED** [review]
remove those 4 added files under unityEngine.Content.Addressable
image

**Comment by Ryan089** [comment]
> remove those 4 added files under unityEngine.Content.Addressable image

Is that a .gitignore issue?

**Comment by stilnat** [comment]
@Ryan089 I'm unsure, I'm gonna ask on discord.

**Comment by stilnat** [comment]
Good for me, just need our file shuffling expert to validate.

**Review by stilnat — DISMISSED** [review]

**Review by stilnat — DISMISSED** [review]

**Review by cosmiccoincidence — APPROVED** [review]
lgtm.

I don't see any errors when play testing or building.

**Pull request merged**
