### PR TITLE
Clean Up: Art folder

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
## Summary
- Moves files to appropriate locations
- Removes a few unused files/folders
- Maybe a few renames as well

This PR only cleans up the Art folder. The Content folder will come next.

### CODE REVIEW

**Comment by stilnat** [comment]
- Change Slot_Fill , Slot_Inset, Slot_Outline with PascalCase.
- png files are not respecting PascalCase is that on purpose ?
- There's at least 4 different naming style on .png (and also for a few .fbx) : "SquareWindows", "squareWindows", "Square-Windows", "Square_windows".

We should maybe make all of this PascalCase ?

The folder hierarchy is clean and solid.
No bugs or exception when messing around (Solid testing method, approved by 1955 best programmers).

**Comment by cosmiccoincidence** [comment]
Renamed all the files (and folders) in the Art folder to PascalCase *except* the 'TextMesh Pro' folder and contents because those are an external library thing so changing the names would likely break it.

**Review by stilnat — CHANGES_REQUESTED** [review]
Almost there ! Some files still have their first letter lower case, like boozedispenser, interactionIcons and other stuff, correct that and good to go !
image

**Comment by cosmiccoincidence** [comment]
Hmm, I know I changed these folders using that rename tool I linked in discord...
I think Unity (or maybe GitHub) doesn't recognize a filename change if the only change is to capitalization.

**Comment by cosmiccoincidence** [comment]
Try pulling these commits and checking the files in the image above and see if they were updated on your end.

(I'm also getting an error preventing me from running the game, see if you get it too.)

**Comment by TaylorNAlbarnaz** [comment]
Confusing, why are the models for mugs in the Art folder, but the models for every other item in the Content folder?

**Comment by cosmiccoincidence** [comment]
Models belong in the Art folder yeah, but this PR is only cleaning up the Art folder so those other models will get moved over in my next clean up PR.

**Comment by cosmiccoincidence** [comment]
Going to just remake this. Solving the meta data issue will take more time than just breaking it up due to how slow github load the files page when there are 1600 files changed.

**Pull request closed without merging**
