### PR TITLE
Fix project materials

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
- Corrects import settings for materials for all fbxs
- Updates all prefabs with correct materials
- Updates a few materials themselves
- Moves the materials folder from Art to Content

### CODE REVIEW

**Comment by TimFinucane** [comment]
Why are materials moved to the Content folder?

**Comment by cosmiccoincidence** [comment]
.mats are made in Unity

**Comment by TimFinucane** [comment]
Ok, makes sense then.

**Comment by cosmiccoincidence** [comment]
Need to resolve these conflicts...

**Pull request merged**
