### PR TITLE
Rename System To SubSystem

### PR DESCRIPTION
**Pull request by devsleeper**
## Summary
Renamed "System" to "SubSystem" as noted,  though I could not find the "SystemLocator.cs" mentioned.  Also renamed some unmentioned which felt relevant like "CameraSystem" to CameraSubSystem since I'm assuming these are supposed to follow the flow as well.  Please have a thorough look to confirm it's as expected.. (new here)🙂 

## Changes to Files
#1011

### CODE REVIEW

**Comment by iamteapot422** [comment]
SystemLocator is already renamed to Subsystems

**Comment by joaoburatto** [comment]
LGTM, will test later.

**Comment by cosmiccoincidence** [comment]
File conflicts need to be resolved.

**Comment by stilnat** [comment]
@devsleeper Hi there and welcome ! Sorry for the conflicts, we need to be more careful when merging other stuff. I can take care of it if you'd like to, or let me know if you feel like doing it yourself. Good job !

**Comment by devsleeper** [comment]
@stilnat no worries, I'll be back around Saturday/Sunday to see to it if not already resolved.

**Comment by stilnat** [comment]
@devsleeper Hey, sorry about the long delay, I understand you closed it, things have been slow recently there and we need to get our shit together regarding PR's review. My apologies.

**Comment by joaoburatto** [comment]
All the devs have work and life before SS3D. We can't get everything instantly.

**Comment by devsleeper** [comment]
@joaoburatto I also have a life outside, and realized I would not be able to commit to fixing a conflict that arises potentially weeks after the rename pr was posted.  We are just at a different pace.

Its not fair on you guys to open something and then leave it for dead as my attention is pulled elsewhere, so I removed myself from the equation.

No hate to you guys, sorry for any confusion this caused.

**Comment by stilnat** [comment]
@joaoburatto it's not about time, it's about priorities. We know that a renaming PR is easily broken, and we should have made the effort of reviewing that first, especially because it's an open issue, and it's a new contributor. I would not be here if that was how my first PR was received. We've all been working on other stuff for SS3D too those last weeks, so lack of time is no excuses. 

@devsleeper No need to be sorry, that's another occasion for us to acknowledge and discuss our weaknesses. We hope that with basic features implemented the project gets traction and we get up to pace. Feel free to come back and contribute at any time.

**Pull request closed without merging**
