### PR TITLE
Add pressing "T" to open and focus chat

### LINKED ISSUE #781: "T" to activate chat
## Summary

Sticking with SS13 tradition again on this one... <kbd>T</kbd> will be used to activate the chat window to allow the user to quickly start typing.

## Goal 

1. Set the <kbd>T</kbd> key to activate the chat window. If the chat window is closed, it will open AND activate the window.
2. Add this new control to the control settings UI.

### PR DESCRIPTION
**Pull request by calmilamsy**
## Summary

Adds the ability to press "T" to open and focus chat.

If chat is hidden, it unhides chat and focuses on the input textbox.

## Changes to Files

Added a new public method (ChatWindow.FocusInputField) that does what it says on the tin.
Added some extra code to handle the keypress and unhiding+focusing logic inside ToggleChat.Update.
Added the key to the keybindings window as well.

## Known Issues

Might also be an idea to add a config option for re-hiding the chat window once the user has finished typing in it.

## Fixes

Closes #781

### CODE REVIEW

**Review by cosmiccoincidence — COMMENTED** [review]
uh... It's not working for me.

**Review by Ryan089 — CHANGES_REQUESTED** [review]
The new control has been added to the settings menu.

The actual functionality doesn't currently work, as the "Focus Chat" input hasn't been set. It appears that you simply haven't ProjectSettings/InputManager.asset into your commit - it should have been changed when you added Focus Chat to it. When I manually added it in, the PR worked as described.

**Comment by calmilamsy** [comment]
Should be fixed now. Turns out I didnt commit my InputManager changes.

**Review by cosmiccoincidence — APPROVED** [review]
There we go. Good work!

**Pull request merged**
