### PR TITLE
Switch locker light

### LINKED ISSUE #1108: Locker Lock Light
## Summary

Lockers have been added as our first object using the ID permissions system (#1053 ), meaning you can lock and unlock lockers using the IDs. Now we should visually indicate to the player whether a locker is locked or not by using the light object in the lock prefab.

Currently the light object is using the PalleteEmission material but this may require using a custom material. 

## Goal 

- Turn the light object's material green when the locker is unlocked.
- Turn the light object's material red when the locker is locked.

### PR DESCRIPTION
**Pull request by iamteapot422**
Closes #1108

### CODE REVIEW

**Review by stilnat — DISMISSED** [review]
Looks neat ! Small issue with syncing though :
image

The light stays always green for client, whether client or host is switching it. 
Both client and host can unlock it, but it only appears on host. 
Let me know if you need help with that.
Also, does it do anything other than switching the light color for now ?

**Comment by cosmiccoincidence** [comment]
The light seems to be effecting all things that use the emission material. This should not be the case. Instead you should make a custom material that switches based on the trigger, that way it only effects things that use that trigger. Also if 2 lockers use the same light material, the light shouldnt change on both lockers at the same time.

I recommend asking @Seteron how he did the airlock lights in the outdated branch. Which I believe was implemented here: https://github.com/RE-SS3D/SS3D/pull/504

Edit: Also, please add description to PR.

**Comment by Seteron** [comment]
MaterialPropertyBlock is best practice for this use case. Here's a simple usage example.
```cs
public class MyClass : MonoBehaviour
{
    private MaterialPropertyBlock propertyBlock;
    private Renderer renderer;
     
    void Start()
    {
         renderer = GetComponent<Renderer>();
         propertyBlock = new MaterialPropertyBlock();
    }
     
    void DoThing()
    {
     
         propertyBlock.SetColor("_Color", Color.red);
         renderer.SetPropertyBlock(propertyBlock);
    } 
}
```

**Review by stilnat — APPROVED** [review]
good to go

**Pull request merged**
