### PR TITLE
Interaction rework

### LINKED ISSUE #159: Decouple inventory and interactions
**Description**
Create a 'ToolSelector' interface that the inventory or hands implements and the interaction system connects to.

### LINKED ISSUE #184: Interaction Distance on All Interactions
# Summary

All interactions should by default be limited to within a certain range. This should be done in the interaction handler and should be modifiable in the unity editor. By default it should be 1.5f.

You do not need to have an opt-out or override for individual interactions, we will do that later if needed.

### LINKED ISSUE #238: Interactions Distance Interruption
### Summary

Interactions should be interrupted when the player moves too far away.

### Current Behavior

Currently, you can start a construction with the crowbar or wrench then walk away while the delayed interaction timer is going and the interaction will still complete despite the player walking away from the location of where the interaction happened.

### Steps to Reproduce

- Grab crowbar or wrench
- Start a construction
- Walk away
- See the construction job complete when the delayed interaction timer is finished, despite having walked away.

### Expected Behavior

The interaction should be interrupted if the player moves outside the interaction distance.

### LINKED ISSUE #270: Dropping item disables components
### Summary
Dropping items breaks custom functionality set in components like scripts or audiosources

### Current Behavior
The inventory system disables items when stored in a container or when in hand. When placed back into the world, the item is made active, but not all Components are activated again. This breaks items that have active scripts or other components like the Honk.

The inventory system does seem to enable some components (boxcolider) when placed back into the world. 

### Steps to Reproduce
Grab the Honk from a desk. Honk a few times. Drop the honk and pick it up again. Try honking again.

afbeelding

### Expected Behavior
Placing items back into the world should enable all components (scripts, AudioSources, etc).

### LINKED ISSUE #289: Blowtorches self completing task.
Dropped blowtorches will continue completing their task.

Pick up a blowtorch and turn it on. Begin reinforcing a floor tile, and set it down. The blowtorch will continue.

The blowtorch should stop all current tasks when dropped.

### LINKED ISSUE #293: Progress bars are attached to the held item, not the character.
Title

### PR DESCRIPTION
**Pull request by Alainx277**
### Summary

Changes the interaction system to a more generic variant.

## Changes to Files

Almost all files relating to interactions have been touched.

## Technical Notes

Interactions are now no longer implemented directly in game objects. As we are still working with Unity's old MonoBehaviours, most of the system has been created on the basis of game objects (this can be switched later).

#### IInteraction
An interaction which can act on the game. In the new system all interactions have continuous methods like Update, which can be left empty if not used.
#### IInteractionSource
This is what causes interactions. It can also modify the interactions which were generated by interaction targets. It keeps track of interactions and is responsible for updating them.
#### IInteractionTarget
The target of an interaction. It can generate interactions depending on the interaction event.
#### InteractionEvent
Stores information about an interaction. Always includes a source.
#### InteractionSourceNetworkBehaviour
Base class for interaction sources which are network behaviours. A core part of this new system, as it 
runs the interaction life cycle and syncs cancellations.
#### InteractionTargetNetworkBehaviour
Base class for network behaviours which generate interactions.
#### IClientInteraction
The client part of an interaction (optional). Can be used to display things to the player.
#### IGameObjectProvider
Interface for interaction targets/sources to expose their game object.
#### Interaction handler
Invokes interaction logic and starts client interactions. Goes on each player's game object.

## Known issues

While sorting is possible now, there is still no good method of doing so. I appreciate any input.

## Fixes

Resolves #159
Resolves #238 
Resolves #184
Fixes #270 
Fixes #289 
Fixes #293

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
I'd avoid PRs with this many files changed in the future. Try to break them up if possible.

**Comment by Alainx277** [comment]
> Please try to avoid making PRs with this many files changed in the future. Try to break them up if possible.

I can't really make a pr to change the interaction system and leave the game broken can I? Also, all further fixes depend on these changes, and I've been waiting a few days now...

**Comment by cosmiccoincidence** [comment]
If you made the PRS at the same time it should be fine... so if #1 breaks something as long as it's fixed in the next one it should be okay. I understand there is a fine balance between making PRs small and trying to avoid extra work for yourself or the reviewers.

**Comment by cosmiccoincidence** [comment]
After merging in master and clearing out the conflicts I was still left with 1 major error which has to do with a new interaction for the energy sword. Clear up this error and allow us for another play test and it should be good to go.

**Comment by Alainx277** [comment]
> After merging in master and clearing out the conflicts I was still left with 1 major error which has to do with a new interaction for the energy sword. Clear up this error and allow us for another play test and it should be good to go.

Fixed the energy sword. The merge also broke some prefabs, let me know if you find more broken stuff.

**Comment by Alainx277** [comment]
> it seems some problems were introduced when merging prefabs

Cosmic whyyyy

**Comment by cosmiccoincidence** [comment]
I thought you fixed them after I merged master... I haven't touched this since then.

**Comment by Alainx277** [comment]
> I thought you fixed them after I merged master...? I haven't touched this since then.
> 
> Do we know which prefabs?

Thought that was just Unity being Unity.
I'm gonna need to manually copy the prefabs again, were there any major changes to them?

**Comment by cosmiccoincidence** [comment]
Yeah, recently John reported most of them from Blender and imported them back into Unity as many had incorrect rotations and such.

**Comment by cosmiccoincidence** [comment]
Window and Reinforced window prefabs are messed up... I can put a fix in for them tho.

**Comment by cosmiccoincidence** [comment]
So ya, when I play tested it, the window and reinforced windows were missing from the scene I fixed those... but there is also another problem.. the character seems completely broken..
https://cdn.discordapp.com/attachments/483813870494941188/713564385108557895/iGOVbO9u3P.mp4

**Comment by Alainx277** [comment]
> So ya, when I play tested it, the window and reinforced windows were missing from the scene I fixed those... but there is also another problem.. the character seems completely broken..

Unable to reproduce that at all. The character is working just fine for me.
Anything in the console?

**Comment by cosmiccoincidence** [comment]
The connection script in the window and r window prefabs are still messed up.  I'll maybe have times to finish my review and fix them.

**Pull request merged**
